name: 'Node Video Streaming Server'
description: ''
runs: 'Carlos Santos'

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
              node-version: '14'
        - run: npm install
        - run: npm test